name: stora
description: "Stora - Inventory management for e-commerce"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.4
  intl: any

  # Routing
  go_router: ^14.8.1

  # Storage
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3

  # Theme
  json_annotation: ^4.8.1


dev_dependencies:
  build_runner: any
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/assets/images/
    - lib/assets/icons/
    - lib/l10n/languages/